/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("item").del();
  await knex("item").insert([
    { item_name: "アイロン", initials: "あ", type_id: 11 },
    { item_name: "アイロンプリント紙", initials: "あ", type_id: 5 },
    { item_name: "空き缶のふた(金属製)", initials: "あ", type_id: 2 },
    { item_name: "空きビン(農薬)", initials: "あ", type_id: 7 },
    { item_name: "空きビンのふた(金属製)", initials: "あ", type_id: 2 },
    { item_name: "油(食用)", initials: "あ", type_id: 7 },
    { item_name: "アクリルスタンド", initials: "あ", type_id: 5 },
    { item_name: "雨どい", initials: "あ", type_id: 5 },
    { item_name: "網戸(枠、アルミサッシ)", initials: "あ", type_id: 8 },
    { item_name: "網戸のネット(ステンレス製)", initials: "あ", type_id: 6 },
    { item_name: "網戸のネット(プラスチック製)", initials: "あ", type_id: 5 },
    { item_name: "アルミ缶(飲料、食用品)", initials: "あ", type_id: 2 },
    { item_name: "アルミホイル", initials: "あ", type_id: 6 },
    { item_name: "アルミホイルの芯", initials: "あ", type_id: 4 },
    { item_name: "アルミホイルの外箱", initials: "あ", type_id: 4 },
    { item_name: "アルミホイルの外箱の刃(金属製)", initials: "あ", type_id: 6 },
    { item_name: "安全靴", initials: "あ", type_id: 7 },
    { item_name: "石", initials: "い", type_id: 6 },
    { item_name: "衣装ケース(プラスチック製)", initials: "い", type_id: 8 },
    { item_name: "いす", initials: "い", type_id: 8 },
    { item_name: "一升びん", initials: "い", type_id: 2 },
    { item_name: "一升びんのふた(金属製)", initials: "い", type_id: 2 },
    { item_name: "一斗缶", initials: "い", type_id: 6 },
    { item_name: "イヤホン(有線)", initials: "い", type_id: 9 },
    { item_name: "イヤホン(ワイヤレスタイプ)", initials: "い", type_id: 1 },
    { item_name: "衣類(布製、皮製、ビニール製)", initials: "い", type_id: 9 },
    { item_name: "衣類乾燥機", initials: "い", type_id: 12 },
    { item_name: "インスタンスカメラ", initials: "い", type_id: 1 },
    { item_name: "インスタントコーヒーのびん", initials: "い", type_id: 2 },
    {
      item_name: "インスタントコーヒーのびんのふた(プラスチック製)",
      initials: "い",
      type_id: 5,
    },
    {
      item_name: "インスタントコーヒーのびんの密閉ふた(紙製)",
      initials: "い",
      type_id: 4,
    },
    { item_name: "植木鉢(陶磁器類)", initials: "う", type_id: 7 },
    { item_name: "植木鉢(プラスチック類)", initials: "う", type_id: 5 },
    {
      item_name: "ウォーターサーバーのタンク(プラスチック類)",
      initials: "う",
      type_id: 5,
    },
    {
      item_name: "ウォーターサーバー(ペットボトル)",
      initials: "う",
      type_id: 3,
    },
    { item_name: "浮き輪", initials: "う", type_id: 5 },
    { item_name: "うちわ(プラスチック製)", initials: "う", type_id: 5 },
    { item_name: "腕時計", initials: "う", type_id: 1 },
    { item_name: "梅酒のびん", initials: "う", type_id: 2 },
    { item_name: "エアコン", initials: "え", type_id: 12 },
    { item_name: "エアコン(室外機)", initials: "え", type_id: 12 },
    { item_name: "絵本", initials: "え", type_id: 9 },
    { item_name: "延長コード", initials: "え", type_id: 9 },
    { item_name: "オイル缶", initials: "お", type_id: 6 },
    { item_name: "オーブンレンジ", initials: "お", type_id: 9 },
    { item_name: "おもちゃ(金属製)", initials: "お", type_id: 6 },
    { item_name: "おもちゃ(プラスチック製)", initials: "お", type_id: 5 },
    { item_name: "おもちゃ(木製、布製)", initials: "お", type_id: 7 },
    { item_name: "カーテン", initials: "か", type_id: 1 },
    { item_name: "カーペット", initials: "か", type_id: 8 },
    { item_name: "鏡(手鏡)", initials: "か", type_id: 7 },
    { item_name: "傘", initials: "か", type_id: 7 },
    { item_name: "かばん(布製、皮製)", initials: "か", type_id: 7 },
    { item_name: "ガラス", initials: "か", type_id: 6 },
    { item_name: "緩衝材", initials: "か", type_id: 5 },
    { item_name: "乾電池", initials: "か", type_id: 1 },
    { item_name: "カタログ", initials: "か", type_id: 9 },
    { item_name: "キーボード", initials: "き", type_id: 12 },
    { item_name: "着物", initials: "き", type_id: 9 },
    { item_name: "靴(皮製、布製)", initials: "く", type_id: 7 },
    { item_name: "クリアファイル", initials: "く", type_id: 5 },
    { item_name: "クリスマスツリー", initials: "く", type_id: 8 },
  ]);
};
