/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("item").del();
  await knex("item").insert([
    { item_name: "アイロン", initials: "あ", type_id: 11 },
    { item_name: "アイロンプリント紙", initials: "あ", type_id: 5 },
    { item_name: "空き缶のふた(金属製)", initials: "あ", type_id: 2 },
    { item_name: "空きビン(農薬)", initials: "あ", type_id: 7 },
    { item_name: "空きビンのふた(金属製)", initials: "あ", type_id: 2 },
    { item_name: "油(食用)", initials: "あ", type_id: 7 },
    { item_name: "アクリルスタンド", initials: "あ", type_id: 5 },
    { item_name: "雨どい", initials: "あ", type_id: 5 },
    { item_name: "網戸(枠、アルミサッシ)", initials: "あ", type_id: 8 },
    { item_name: "網戸のネット(ステンレス製)", initials: "あ", type_id: 6 },
    { item_name: "網戸のネット(プラスチック製)", initials: "あ", type_id: 5 },
    { item_name: "アルミ缶(飲料、食用品)", initials: "あ", type_id: 2 },
    { item_name: "アルミホイル", initials: "あ", type_id: 6 },
    { item_name: "アルミホイルの芯", initials: "あ", type_id: 4 },
    { item_name: "アルミホイルの外箱", initials: "あ", type_id: 4 },
    { item_name: "アルミホイルの外箱の刃(金属製)", initials: "あ", type_id: 6 },
    { item_name: "安全靴", initials: "あ", type_id: 7 },
    { item_name: "石", initials: "い", type_id: 6 },
    { item_name: "衣装ケース(プラスチック製)", initials: "い", type_id: 8 },
    { item_name: "いす", initials: "い", type_id: 8 },
    { item_name: "一升びん", initials: "い", type_id: 2 },
    { item_name: "一升びんのふた(金属製)", initials: "い", type_id: 2 },
    { item_name: "一斗缶", initials: "い", type_id: 6 },
    { item_name: "イヤホン(有線)", initials: "い", type_id: 9 },
    { item_name: "イヤホン(ワイヤレスタイプ)", initials: "い", type_id: 1 },
    { item_name: "衣類(布製、皮製、ビニール製)", initials: "い", type_id: 9 },
    { item_name: "衣類乾燥機", initials: "い", type_id: 12 },
    { item_name: "インスタンスカメラ", initials: "い", type_id: 1 },
    { item_name: "インスタントコーヒーのびん", initials: "い", type_id: 2 },
    {
      item_name: "インスタントコーヒーのびんのふた(プラスチック製)",
      initials: "い",
      type_id: 5,
    },
    {
      item_name: "インスタントコーヒーのびんの密閉ふた(紙製)",
      initials: "い",
      type_id: 4,
    },
    { item_name: "植木鉢(陶磁器類)", initials: "う", type_id: 7 },
    { item_name: "植木鉢(プラスチック類)", initials: "う", type_id: 5 },
    {
      item_name: "ウォーターサーバーのタンク(プラスチック類)",
      initials: "う",
      type_id: 5,
    },
    {
      item_name: "ウォーターサーバー(ペットボトル)",
      initials: "う",
      type_id: 3,
    },
    { item_name: "浮き輪", initials: "う", type_id: 5 },
    { item_name: "うちわ(プラスチック製)", initials: "う", type_id: 5 },
    { item_name: "腕時計", initials: "う", type_id: 1 },
    { item_name: "梅酒のびん", initials: "う", type_id: 2 },
    { item_name: "エアコン", initials: "え", type_id: 12 },
    { item_name: "エアコン(室外機)", initials: "え", type_id: 12 },
    { item_name: "絵本", initials: "え", type_id: 9 },
    { item_name: "延長コード", initials: "え", type_id: 9 },
    { item_name: "オイル缶", initials: "お", type_id: 6 },
    { item_name: "オーブンレンジ", initials: "お", type_id: 9 },
    { item_name: "おもちゃ(金属製)", initials: "お", type_id: 6 },
    { item_name: "おもちゃ(プラスチック製)", initials: "お", type_id: 5 },
    { item_name: "おもちゃ(木製、布製)", initials: "お", type_id: 7 },
    { item_name: "カーテン", initials: "か", type_id: 1 },
    { item_name: "カーペット", initials: "か", type_id: 8 },
    { item_name: "鏡(手鏡)", initials: "か", type_id: 7 },
    { item_name: "傘", initials: "か", type_id: 7 },
    { item_name: "かばん(布製、皮製)", initials: "か", type_id: 7 },
    { item_name: "ガラス", initials: "か", type_id: 6 },
    { item_name: "緩衝材", initials: "か", type_id: 5 },
    { item_name: "乾電池", initials: "か", type_id: 1 },
    { item_name: "カタログ", initials: "か", type_id: 9 },
    { item_name: "キーボード", initials: "き", type_id: 12 },
    { item_name: "着物", initials: "き", type_id: 9 },
    { item_name: "靴(皮製、布製)", initials: "く", type_id: 7 },
    { item_name: "クリアファイル", initials: "く", type_id: 5 },
    { item_name: "クリスマスツリー", initials: "く", type_id: 8 },
    { item_name: "化粧品の外箱", initials: "け", type_id: 4 },
    { item_name: "化粧品のびん", initials: "け", type_id: 2 },
    { item_name: "化粧品のびんのふた", initials: "け", type_id: 5 },
    { item_name: "化粧品の容器", initials: "け", type_id: 5 },
    { item_name: "結束バンド", initials: "け", type_id: 5 },
    { item_name: "コップ(ガラス、陶磁器)", initials: "こ", type_id: 6 },
    { item_name: "コップ(プラスチック)", initials: "こ", type_id: 5 },
    { item_name: "コンビニ弁当の容器", initials: "こ", type_id: 5 },
    { item_name: "雑誌", initials: "さ", type_id: 9 },
    {
      item_name: "サンダル(プラスチック製、ゴム類)",
      initials: "さ",
      type_id: 5,
    },
    { item_name: "シーツ", initials: "し", type_id: 9 },
    { item_name: "下着類", initials: "し", type_id: 9 },
    { item_name: "じゅうたん", initials: "し", type_id: 8 },
    { item_name: "食器棚", initials: "し", type_id: 8 },
    { item_name: "食器類(ガラス、陶磁器)", initials: "し", type_id: 6 },
    { item_name: "食器類(プラスチック類)", initials: "し", type_id: 5 },
    { item_name: "水筒(ステンレス製)", initials: "す", type_id: 6 },
    { item_name: "水筒(プラスチック製)", initials: "す", type_id: 5 },
    { item_name: "スーツケース", initials: "す", type_id: 8 },
    { item_name: "スプーン(金属製)", initials: "す", type_id: 6 },
    { item_name: "スプーン(プラスチック製)", initials: "す", type_id: 5 },
    { item_name: "スニーカー", initials: "す", type_id: 7 },
    { item_name: "スリッパ", initials: "す", type_id: 7 },
    { item_name: "生理用品", initials: "せ", type_id: 7 },
    { item_name: "ソファー", initials: "そ", type_id: 8 },
    { item_name: "タンス", initials: "た", type_id: 8 },
    { item_name: "ダンボール", initials: "た", type_id: 9 },
    { item_name: "机", initials: "つ", type_id: 8 },
    { item_name: "電気毛布", initials: "て", type_id: 7 },
    { item_name: "電池類", initials: "て", type_id: 1 },
    { item_name: "時計", initials: "と", type_id: 9 },
    { item_name: "ドライヤー", initials: "と", type_id: 9 },
    { item_name: "人形(布製)", initials: "に", type_id: 7 },
    { item_name: "人形(プラスチック)", initials: "に", type_id: 5 },
    { item_name: "ぬいぐるみ", initials: "ぬ", type_id: 7 },
    {
      item_name: "布類(古着、毛布、シーツ、タオル)",
      initials: "ぬ",
      type_id: 9,
    },
    {
      item_name: "布類(古着、毛布、シーツ、タオル以外)",
      initials: "ぬ",
      type_id: 7,
    },
    { item_name: "剥製", initials: "は", type_id: 7 },
    { item_name: "ハンガー(金属製)", initials: "は", type_id: 6 },
    { item_name: "ハンガー(プラスチック製)", initials: "は", type_id: 5 },
    { item_name: "ハンガー(木製)", initials: "は", type_id: 7 },
    { item_name: "ハンカチ", initials: "は", type_id: 9 },
    { item_name: "フィギュア", initials: "ふ", type_id: 5 },
    { item_name: "フォーク(金属製)", initials: "ふ", type_id: 6 },
    { item_name: "フォーク(プラスチック製)", initials: "ふ", type_id: 5 },
    { item_name: "服", initials: "服", type_id: 9 },
    { item_name: "布団(綿、羽毛入)", initials: "ふ", type_id: 9 },
    { item_name: "ベルト", initials: "へ", type_id: 7 },
    { item_name: "ベッド", initials: "へ", type_id: 8 },
    { item_name: "帽子", initials: "ほ", type_id: 9 },
    { item_name: "本", initials: "ほ", type_id: 10 },
    { item_name: "枕", initials: "ま", type_id: 7 },
    { item_name: "ミシン", initials: "み", type_id: 9 },
    { item_name: "眼鏡", initials: "め", type_id: 6 },
    { item_name: "やかん", initials: "や", type_id: 6 },
    { item_name: "浴衣", initials: "ゆ", type_id: 9 },

    { item_name: "レジャーシート", initials: "れ", type_id: 5 },
    { item_name: "ろうそく", initials: "ろ", type_id: 7 },
    { item_name: "リュックサック", initials: "り", type_id: 7 },
    { item_name: "パソコン", initials: "は", type_id: 13 },
    { item_name: "廃油", initials: "は", type_id: 14 },
  ]);
};
